# Generated by Django 4.0.1 on 2022-02-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='owener',
            new_name='owner',
        ),
    ]
