# Generated by Django 4.0.1 on 2022-02-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_pwner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pwner',
            new_name='owner',
        ),
    ]
